##DA - Working with pandas

#Session 2

In [ ]:
import pandas as pd


1.Download a CSV file of IPL match results from Kaggle or any open dataset, then use pandas read_csv() to load it into a DataFrame and display the first 10 rows using head().

In [ ]:
df = pd.read_csv("matches.csv")
df.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba

2.Find a small Excel file of your own mobile expenses (or create one with 5-10 rows), then use pandas read_excel() to load it and print the last 3 rows using tail().

In [ ]:
mf =pd.read_excel("mobile_expenses.xlsx")
mf.tail(3)

         Date          Expense  Amount
7  15-09-2026   Charging Cable     299
8  17-09-2026    Mobile Repair     800
9  20-09-2026  Mobile Recharge     299

3.Use describe() and info() on a DataFrame loaded from a Zomato restaurant dataset (or any food delivery data you can find online), and write down 2 insights about the data (for example: number of restaurants, missing values, or average ratings).<br><br><em><strong>Hint:</strong> Focus on what info() and describe() reveal about columns and data types.</em>

In [ ]:
zf = pd.read_csv("zometo_dataset.csv")
print("----info method---")
zf.info()
print("----decribe method----")
print(zf.describe())

print("----insights----")
print("Insight 1: There are 514 restaurant records in the dataset. The average restaurant rating is approximately 3.7.")
print("Insight 2: The dish_liked column has 255 missing values (514 total − 259 non-null), while the type column has 19 missing values. This shows that some restaurant information is missing in the dataset.")

----info method---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    514 non-null    int64
 1   name          514 non-null    object
 2   online_order  514 non-null    object
 3   book_table    514 non-null    object
 4   rating        514 non-null    float64
 5   votes         514 non-null    int64
 6   location      514 non-null    object
 7   rest_type     514 non-null    object
 8   dish_liked    259 non-null    object
 9   cuisines      513 non-null    object
 10  approx_cost   514 non-null    object
 11  type          495 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 48.3+ KB
----decribe method----
       Unnamed: 0      rating        votes
count  514.000000  514.000000   514.000000
mean   294.935798    3.537160   219.268482
std    168.150580    0.818357   456.160288
min      0.000000    0.000000     0.000000
25%    161.250000    3.400000    21.000000
50%    299.000000    3.700000    67.000000
75%    435.750000    3.900000   216.750000
max    586.000000    4.600000  4884.000000
----insights----
Insight 1: There are 514 restaurant records in the dataset. The average restaurant rating is approximately 3.7.
Insight 2: The dish_liked column has 255 missing values (514 total − 259 non-null), while the type column has 19 missing values. This shows that some restaurant information is missing in the dataset.

4.Export the DataFrame from your IPL or food delivery dataset to a new CSV file called 'filtered_data.csv', but only include the first 20 rows.

In [ ]:
df = pd.read_csv("zometo_dataset.csv")
filtered_data = df.head(20)
filtered_data.to_csv("filtered_data.csv", index=False)

dff = pd.read_csv("filtered_data.csv")
dff

,Unnamed: 0,name,online_order,book_table,rating,votes,location,rest_type,dish_liked,cuisines,approx_cost,type
0,0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet
5,5,Timepass Dinner,Yes,No,3.8,286,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,Buffet
6,6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6,8,Mysore Road,Casual Dining,NaN,"North Indian, South Indian, Andhra, Chinese",800,Buffet
7,7,Onesta,Yes,Yes,4.6,2556,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Cafes
8,8,Penthouse Cafe,Yes,No,4.0,324,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,NaN
9,10,Smacznego,Yes,No,4.2,504,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,Cafes
10,11,CafDown The Alley,Yes,No,4.1,402,Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500,Cafes
11,12,Cafe Shuffle,Yes,Yes,4.2,150,Banashankari,Cafe,"Mocktails, Peri Fries, Lasagne, Pizza, Chicken...","Cafe, Italian, Continental",600,Cafes
12,13,The Coffee Shack,Yes,Yes,4.2,164,Banashankari,Cafe,"Coffee, Spaghetti, Pancakes, Nachos, Pasta, Sa...","Cafe, Chinese, Continental, Italian",500,Cafes
13,14,Caf-Eleven,No,No,4.0,424,Banashankari,Cafe,"Sandwich, Omelette, Ice Tea, Virgin Mojito, Ho...","Cafe, Continental",450,Cafes
14,15,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Cafes
15,16,Cafe Vivacity,Yes,No,3.8,90,Banashankari,Cafe,"Garlic Bread, Burgers, Sandwiches, Pizza, Hot ...",Cafe,650,Cafes
16,17,Catch-up-ino,Yes,No,3.9,133,Banashankari,Cafe,"Momos, Mushroom Bruschettas, Jalapeno Cheeseba...","Cafe, Fast Food, Continental, Chinese, Momos",800,Cafes
17,18,Kirthi's Biryani,Yes,No,3.8,144,Banashankari,Cafe,"Pasta, Gelato, Garlic Bread, Mojito, Nachos, P...","Chinese, Cafe, Italian",700,Cafes
18,19,T3H Cafe,No,No,3.9,93,Banashankari,Cafe,"Cheese Maggi, Peri Peri Fries, Pasta Arrabiata","Cafe, Italian, American",300,Cafes
19,20,360 Atoms Restaurant And Cafe,Yes,No,3.1,13,Banashankari,Cafe,NaN,"Cafe, Chinese, Continental, Italian",400,Cafes

5.Load any dataset of your choice (not the one used in the class demo), and export it to Excel format with a custom sheet name like 'Analysis2024'.<br><br><em><strong>Constraint:</strong> Use the to_excel() method and set the sheet_name parameter.</em>

In [ ]:
df = pd.read_csv("Job Posts.csv")
df.to_excel("jobpost_analysis.xlsx",sheet_name="Analysis2024",index=False)

dff = pd.read_excel("jobpost_analysis.xlsx", sheet_name="Analysis2024")
print(dff)

      Unnamed: 0                                          Job_Title  \
0              0                         Data Scientist (NiFi, DHF)
1              1            Data Scientist - Defense & Intelligence
2              2  Fall 2019/Winter 2020 Applied Science Machine ...
3              3  Applied Scientist Fall/Winter 2019 Internship ...
4              4                Data Scientist/Engineer (HDF, NiFi)
...          ...                                                ...
9062        9062                   Senior Business Services Analyst
9063        9063      AVP of Corporate Strategy & Business Strategy
9064        9064                Business Analyst - Registered Nurse
9065        9065                                    Systems Analyst
9066        9066  Sales & Marketing Team Lead - Competative Spor...

                                        Job_Description  \
0     EducationBachelor's DegreeSkillsSQLTime Manage...
1     EducationBachelor's DegreeSkillsNoSQLSQL401(k)...
2     EducationDoctoral DegreeMaster's DegreeSkillsN...
3     EducationDoctoral DegreeMaster's DegreeSkillsN...
4     EducationBachelor's DegreeMaster's DegreeDocto...
...                                                 ...
9062  \r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...
9063  \r\r\r\r\r\nRESPONSIBILITIES:Kforce has a clie...
9064  \r\r\r\r\r\nCompany Overview:\r\r\r\r\r\nCreat...
9065  \r\r\r\r\r\nA leading consultancy is recruitin...
9066  \r\r\r\r\r\nMCO Orlando is currently offering ...

                                               Job_Link
0     https://www.simplyhired.com/job/Tq4KqCrotc06Fp...
1     https://www.simplyhired.com/job/OF7HNEC0sGEgBA...
2     https://www.simplyhired.com/job/WaFb8rbhCLxehi...
3     https://www.simplyhired.com/job/BL2wIHWVfwAAgw...
4     https://www.simplyhired.com/job/1H_ga33Kqka5Ot...
...                                                 ...
9062  https://www.careerbuilder.com/job/J3T26Q6VDXW9...
9063  https://www.careerbuilder.com/job/J3N4Z26H1LX0...
9064  https://www.careerbuilder.com/job/JDD66078BTB8...
9065  https://www.careerbuilder.com/job/J3Q0PN78ZKRP...
9066  https://www.careerbuilder.com/job/J2Y43469NDQ7...

[9067 rows x 4 columns]